version: '3'
services:
  jira-server:
    environment:
      - DB_URL=jdbc:postgresql://db:5432/jira
      - POSTGRES_DB=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./resources:/opt/resources
    depends_on:
      - jira-server