version: '3'
services:
  jira-server:
    environment:
      - DB_URL=jdbc:postgresql://db:5432/jira
      - DB_USERNAME=postgres
      - DB_PASSWORD=qwerty
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jira-server